[build]
publish = "dist"
command = "npm run build"

[build.environment]
NODE_VERSION = "20"

[[redirects]]
from = "/*.html"
to = "/:splat"
status = 301
force = false

[[redirects]]
from = "/:page"
to = "/:page.html"
status = 200
force = false